spring:
  datasource:
    url: jdbc:h2:file:${project.data.root}database\comicbook
    driverClassName: org.h2.Driver
    name: comicbook
    password: comicbook
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
server:
  port: 2608
  servlet:
    context-path: /comicbook/api/v1/
project:
  root: ${user.home}\comicbook\
  data:
    root: ${project.root}data\
    photo: ${project.data.root}photos\
    logo: ${project.data.root}logos\
    bio: ${project.data.root}bio\
    abilities: ${project.data.root}abilities\